[build]
publish = "site_source_files/public"
command = "chmod +x build-site.sh && ./build-site.sh"

[context.production.environment]
HUGO_VERSION = "0.66.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "chmod +x build-site.sh && ./build-site.sh"

[context.deploy-preview.environment]
HUGO_VERSION = "0.66.0"

[context.branch-deploy]
command = "chmod +x build-site.sh && ./build-site.sh"

[context.branch-deploy.environment]
HUGO_VERSION = "0.66.0"
