name: Run Python examples

on:
  workflow_dispatch:
  schedule:
    - cron: '50 22 * * *'
  pull_request:
    branches:
      - trunk
    paths:
      - 'examples/python/**'
  push:
    branches:
      - trunk
    paths:
      - 'examples/python/**'

env:
  DISPLAY: :99
  GITHUB_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}
  GH_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}

jobs:
  test_examples:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v2
    - name: Start Xvfb
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb :99 &
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Install Edge
      uses: browser-actions/setup-edge@latest
    - name: Install Firefox
      uses: abhi1693/setup-browser@v0.3.4
      with:
        browser: firefox
        version: latest
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: ./examples/python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      uses: nick-invision/retry@v2.8.2
      with:
        timeout_minutes: 20
        max_attempts: 3
        command: |
          cd examples/python
          pytest
